version: 2.1

jobs:
  sonarscan_build:
    docker:
      - image: circleci/php:7-zts-buster-node-browsers-legacy
     
    steps:
      - checkout
      #- run: sudo docker-php-ext-install zip
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  sonarcloud_circleci_scan:
    jobs:
      - sonarscan_build:
          context: SonarCloud
