version: 2.1

jobs:
  sonarscan_build:
    docker:
      - image: circleci/php:7-zts-buster-node-browsers-legacy
     
    steps:
      - checkout
      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip
      #- run: composer install -n --prefer-dist
      - run: yarn install
      # prepare the database
      #- run: touch storage/testing.sqlite
      #- run: php artisan migrate --env=testing --database=sqlite_testing --force

      # run tests with phpunit or codecept
      #- run: ./vendor/bin/phpunit
      #- run: ./vendor/bin/codecept build
      #- run: ./vendor/bin/codecept run
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  sonarcloud_circleci_scan:
    jobs:
      - sonarscan_build:
          context: SonarCloud
